# Generated by Django 4.2.7 on 2023-12-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='shared_with_email',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
